use blog;

-- Первые 2 поста

INSERT INTO post (title, subtitle, content, author, author_url, publish_date, image_url, featured) 
values
('The Road Ahead', 
'The road ahead might be paved - it might not be.', 
'', 
'Mat Vogels', 
'images/mat-vogels.png', 
'September 25, 2015', 
'/images/northern-lights.png', 
1),
('From Top Down', 
'Once a year, go someplace you’ve never been before.', 
'', 
'William Wong', 
'/images/william-wong.png', 
'September 25, 2015', 
'/images/air-lanterns.png', 
1), -- Вторые 6 постов
('Still Standing Tall', 
'Life begins at the end of your comfort zone.', 
'', 
'Mat Vogels', 
'/images/william-wong.png', 
'9/25/2015', 
'/images/baloons.png', 
0),
('Sunny Side Up', 
'No place is ever as bad as they tell you it’s going to be.', 
'', 
'Mat Vogels', 
'/images/mat-vogels.png', 
'9/25/2015', 
'/images/bridge.png', 
0),
('Water Falls', 
'We travel not to escape life, but for life not to escape us.', 
'', 
'Mat Vogels', 
'/images/mat-vogels.png', 
'9/25/2015', 
'/images/lake.png', 
0),
('Through the Mist', 
'Travel makes you see what a tiny place you occupy in the world.', 
'', 
'William Wong', 
'/images/william-wong.png', 
'9/25/2015', 
'/images/ocean.png', 
0),
('Awaken Early', 
'Not all those who wander are lost.', 
'', 
'Mat Vogels', 
'/images/mat-vogels.png', 
'9/25/2015', 
'/images/smoke.png', 
0),
('Try it Always', 
'The world is a book, and those who do not travel read only one page', 
'', 
'Mat Vogels', 
'/images/mat-vogels.png', 
'9/25/2015', 
'/images/waterfall.png',
0);
